run:
  tests: true
  issues-exit-code: 1

version: "2"

linters:
  default: none
  enable:
    - gocritic
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
  settings:
    gocognit:
      min-complexity: 25
    funlen:
      lines: 160
      statements: 80
    misspell:
      locale: US
    goconst:
      min-len: 4
      min-occurrences: 4
    dupl:
      threshold: 150
    gocyclo:
      min-complexity: 30
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$


formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/picogrid/go-op
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
